Repository UAlbertaALTLab/cree-intelligent-dictionary, pull requests merged in 2020-06, with the labels that each got.

#416 Update base.html to open new tab/window for Help
  CreeDictionary/CreeDictionary/templates/CreeDictionary/base.html
Labels: Improvement

#421 JavaScript cleanup
  cypress/integration/search.spec.js
  src/dom-utils.js
  src/index.js
  src/loading-bar.js
  src/orthography.js
  src/recordings.js
  src/tooltip.js
Labels: Improvement, javascript

#423 Recordings on the search page (inefficient implementation)
  CreeDictionary/CreeDictionary/templates/CreeDictionary/base.html
  CreeDictionary/CreeDictionary/templates/CreeDictionary/paradigm.html
  CreeDictionary/CreeDictionary/templates/CreeDictionary/word-entries.html
  cypress/integration/recordings.spec.js
  src/index.js
Labels: javascript

#425 Cleanup tooltips
  CreeDictionary/CreeDictionary/templates/CreeDictionary/word-entries.html
  src/css/_tooltip.css
  src/css/styles.css
  src/css/variables.css
  src/index.js
  src/tooltip.js
Labels: javascript

#426 Recordings cleanup
  CreeDictionary/CreeDictionary/templates/CreeDictionary/base.html
  CreeDictionary/CreeDictionary/templates/CreeDictionary/paradigm.html
  src/css/styles.css
  src/recordings.js
Labels: javascript

#433 Remove jQuery
  package-lock.json
  package.json
Labels: javascript

#444 Rank lemma before its syncretic form(s)
  CreeDictionary/API/models.py
  CreeDictionary/tests/API_tests/model_test.py
Labels: python

#449 Refactor altlabel
  CreeDictionary/API/models.py
  CreeDictionary/utils/fst_analysis_parser.py
Labels: python

#451 Create (faster?) lemmas() strategy
  CreeDictionary/tests/API_tests/model_test.py
  CreeDictionary/tests/conftest.py
Labels: python

#441 External speaker links
  CreeDictionary/CreeDictionary/templates/CreeDictionary/about.html
  CreeDictionary/CreeDictionary/templates/CreeDictionary/base.html
  CreeDictionary/CreeDictionary/templates/CreeDictionary/paradigm.html
  cypress/integration/recordings.spec.js
  src/css/styles.css
  src/recordings.js
Labels: Improvement, feature, requires-frontend-work

#452 Action: eslint
  .github/workflows/reformat.yml
  cypress/.eslintrc.yml
  cypress/plugins/index.js
  src/css/postcss.config.js
Labels: javascript

#453 Extend relabeller
  CreeDictionary/API/models.py
  CreeDictionary/tests/utils_tests/relabelling_test.py
  CreeDictionary/utils/fst_analysis_parser.py
  cypress/integration/search.spec.js
Labels: python

#458 change: links from altlab.ualberta.ca -> www.altlab.dev
  CreeDictionary/CreeDictionary/templates/CreeDictionary/about.html
  cypress/integration/recordings.spec.js
  src/recordings.js
Labels: javascript

#459 Use new fields from recordings app to display dialect and speaker bio link
  cypress/fixtures/recording/_search/wâpamêw.json
  src/recordings.js
Labels: Improvement, javascript

#456 change: use SimpleTemplate
  src/recordings.js
  src/simple-template.js
Labels: Refactoring, javascript

#464 Each prefix feature is on its own line
  CreeDictionary/CreeDictionary/templates/CreeDictionary/components/_definition-title.html
  cypress/integration/search.spec.js
Labels: Improvement

#466 feat: cree_example tag to properly render "like: itwêwin" in the current orthography
  CreeDictionary/CreeDictionary/templates/CreeDictionary/components/_definition__elaboration.html
  CreeDictionary/CreeDictionary/templatetags/creedictionary_extras.py
  CreeDictionary/tests/CreeDictionary_tests/test_creedictionary_extras.py
  cypress/integration/orthography.spec.js
Labels: Improvement, python

#468 Improve paradigm button styles
  src/css/styles.css
  src/css/variables.css
  src/index.js
Labels: Improvement, javascript

#471 Slightly better paradigm display
  CreeDictionary/CreeDictionary/templates/CreeDictionary/base.html
  CreeDictionary/CreeDictionary/templates/CreeDictionary/components/paradigm.html
  CreeDictionary/CreeDictionary/templates/CreeDictionary/paradigm.html
  CreeDictionary/CreeDictionary/templates/CreeDictionary/word-detail.html
  CreeDictionary/CreeDictionary/views.py
  src/css/utilities.css
Labels: Improvement

#474 Embetter paradigm layout combiner
  CreeDictionary/utils/enums.py
  CreeDictionary/utils/paradigm_layout_combiner.py
Labels: Improvement, python

#482 Create morphodict app
  CreeDictionary/CreeDictionary/settings.py
  CreeDictionary/morphodict/README.md
  CreeDictionary/morphodict/__init__.py
  CreeDictionary/morphodict/apps.py
  CreeDictionary/morphodict/migrations/__init__.py
  CreeDictionary/morphodict/tests/test_morphodict_init.py
Labels: python

#478 change: Delete fuzzy search
  CreeDictionary/API/apps.py
  CreeDictionary/API/models.py
  CreeDictionary/fuzzy_search/__init__.py
  CreeDictionary/fuzzy_search/cree_fuzzy_search.py
  CreeDictionary/fuzzy_search/fuzzy_searcher.py
  CreeDictionary/tests/CreeFuzzySearcher_tests/__init__.py
  CreeDictionary/tests/CreeFuzzySearcher_tests/search_test.py
  pyproject.toml
Labels: python

#483 refactor: move orthography related things to morphodict
  CreeDictionary/CreeDictionary/orthography.py
  CreeDictionary/CreeDictionary/settings.py
  CreeDictionary/CreeDictionary/templates/CreeDictionary/about.html
  CreeDictionary/CreeDictionary/templates/CreeDictionary/components/_definition-title.html
  CreeDictionary/CreeDictionary/templates/CreeDictionary/components/header.html
  CreeDictionary/CreeDictionary/templates/CreeDictionary/components/paradigm.html
  CreeDictionary/CreeDictionary/templates/CreeDictionary/index.html
  CreeDictionary/CreeDictionary/templates/CreeDictionary/word-detail.html
  CreeDictionary/CreeDictionary/templates/CreeDictionary/word-entries.html
  CreeDictionary/CreeDictionary/templatetags/creedictionary_extras.py
  CreeDictionary/CreeDictionary/urls.py
  CreeDictionary/CreeDictionary/views.py
  CreeDictionary/morphodict/orthography.py
  CreeDictionary/morphodict/templatetags/__init__.py
  CreeDictionary/morphodict/templatetags/morphodict_orth.py
  CreeDictionary/morphodict/tests/test_orth_templatetags.py
  CreeDictionary/morphodict/urls.py
  CreeDictionary/morphodict/views.py
  CreeDictionary/tests/CreeDictionary_tests/test_creedictionary_extras.py
  CreeDictionary/tests/CreeDictionary_tests/test_orth_cookie.py
  CreeDictionary/tests/test_usage_of_morphodict.py
  CreeDictionary/utils/vars.py
  src/orthography.js
Labels: Refactoring, python
